---
- name: "Updating Apt Cache"
  command: apt-get update
  become: true
  become_method: sudo
  changed_when: false

- name: "Upgrade All Packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Updating Apt Cache"
  command: apt-get update
  become: true
  become_method: sudo
  changed_when: false

- name: "Installing Tools via Apt - Ubuntu"
  package:
    name:
      - jq
      - rlwrap
      - flameshot
      - exiftool
      - ca-certificates
      - curl
      - ntpdate
      - gh
      - pipx
      - sublime-text
      - xclip
      - remmina
      - nautilus
      - sqlite3
      - python3-dev
      - build-essential
      - libssl-dev 
      - libffi-dev
      - ldap-utils
      - python3.12-dev
      - nmap
      - gobuster
    state: latest
  become: true
  become_method: sudo
  when: ansible_distribunsible_distribution|lower == 'ubuntu'


- name: "Installing Tools via Apt - Parrot"
  package:
    name:
      - jq
      - rlwrap
      - flameshot
      - exiftool
      - ca-certificates
      - curl
      - ntpdate
      - gh
      - pipx
      - sublime-text
      - xclip
      - remmina
      - nautilus
      - sqlite3
      - python3-dev
      - build-essential
      - libssl-dev 
      - libffi-dev
      - ldap-utils
      - powershell
      - python3.12-dev
    state: latest
  become: true
  become_method: sudo
  when: ansible_distribunsible_distribution|lower == 'parrot' or ansible_distribution|lower == 'debian'

