---
- name: Download Brave Browser keyring
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'
  become: true
  become_method: sudo

- name: Download Brave Browser repository sources file
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
    dest: /etc/apt/sources.list.d/brave-browser-release.sources
    mode: '0644'
  become: true
  become_method: sudo

- name: Install Brave Browser
  apt:
    name: brave-browser
    state: present
    update_cache: yes  # This replaces 'sudo apt update'
  become: true
  become_method: sudo