---
- name: "Installing RubyGems"
  apt:
    name: ruby-full
    state: present
  become: true
  become_method: sudo

- name: "Installing tools from Gems"
  gem:
    name: "{{ item }}"
    state: present
    user_install  : false
  loop:
    - logger
    - stringio
    - winrm
    - builder
    - erubi
    - gssapi
    - gyoku
    - httpclient
    - logging
    - little-plugger
    - nori
    - rubyntlm
    - winrm-fs
    - evil-winrm
  become: true
  become_method: sudo

- name: "Set ownership of gem-installed binaries"
  file:
    path: "/usr/local/bin/{{ item }}"
    owner: "{{ ansible_facts['env']['USER'] }}"
    group: "{{ ansible_facts['env']['USER'] }}"
    state: file
  loop:
    - logger
    - stringio
    - winrm
    - builder
    - erubi
    - gssapi
    - gyoku
    - httpclient
    - logging
    - little-plugger
    - nori
    - rubyntlm
    - winrm-fs
    - evil-winrm
  become: true
  become_method: sudo
  ignore_errors: true
