---
# wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo tee /etc/apt/keyrings/sublimehq-pub.asc > /dev/null

- name: "Installing Sublime Text GPG Keys"
  get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /etc/apt/keyrings/sublimehq-pub.asc
    owner: root
    group: root
    mode: 0644
  become: true 
  become_method: sudo

# echo -e 'Types: deb\nURIs: https://download.sublimetext.com/\nSuites: apt/stable/\nSigned-By: /etc/apt/keyrings/sublimehq-pub.asc' | sudo tee /etc/apt/sources.list.d/sublime-text.sources

- name: "Check the existence of /etc/apt/sources.list.d/sublime-text.sources"
  stat: 
    path: /etc/apt/sources.list.d/sublime-text.sources
  register: sublime_text_file
  changed_when: false

- name: "Installing Sublime Text Repository"
  lineinfile:
    path: /etc/apt/sources.list.d/sublime-text.sources
    line: "Types: deb\nURIs: https://download.sublimetext.com/\nSuites: apt/stable/\nSigned-By: /etc/apt/keyrings/sublimehq-pub.asc"
    create: yes
  become: true
  become_method: sudo
  changed_when: false