---
GitHubTools:
  - name: SecLists
    url: "https://github.com/danielmiessler/SecLists"
    destination: "/opt/SecLists"
  
  - name: SharpCollection
    url: "https://github.com/Flangvik/SharpCollection"
    destination: "/opt/SharpCollection"

UVtools:
  - impacket
  - sshuttle

GithubRepositories:
  - url: "https://github.com/ShutdownRepo/pywhisker"
    destination: "tmp/pywhisker"

repositories: 

  - name: bloodyAD
    url: "https://github.com/CravateRouge/bloodyAD"
    destination: "{{ ansible_env.HOME }}/bloodyAD"

  - name: targetedKerberoast
    url: "https://github.com/ShutdownRepo/targetedKerberoast"
    destination: "/tmp/targetedKerberoast"
