---
- name: "Installing Visual Studio Code"
  include_role: 
    name: "gantsign.visual-studio-code"
  vars:
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions:
          - Codeium.codeium
          - snyk-security.snyk-vulnerability-scanner
          - ms-python.python
          - DEVSENSE.phptools-vscode
          - ms-vscode.cpptools
          - golang.Go
          - rust-lang.rust-analyzer
          - ms-vscode.cpptools-extension-pack

- name: "Removing Apt Source List Conflict"
  file:
    path: "/etc/apt/sources.list.d/vscode.sources"
    state: absent
  become: true
  become_method: sudo
  when: ansible_distribution|lower == 'parrot' or ansible_distribution == 'debian'
