#SPDX-License-Identifier: MIT-0
---
DesktopLaunchers:
  - "sublime-text"
  - "vscode"
  - "firefox"
  - "brave-browser"
  - "obsidian"
  - "burp-suite"
  - "caido"
  - "flameshot"

AppPaths:
  - "/usr/bin/subl"
  - "/usr/bin/code"
  - "/usr/bin/firefox"
  - "/usr/bin/brave-browser"
  - "/usr/local/bin/obsidian"
  - "/usr/bin/burpsuite"
  - "/usr/local/bin/caido"
  - "/usr/bin/flameshot"

IconPaths:
  - "/opt/flatpak-icons/apps/scalable/sublimetext.svg"
  - "/opt/flatpak-icons/apps/scalable/visual-studio-code.svg"
  - "/opt/flatpak-icons/apps/scalable/firefox.svg"
  - "/opt/flatpak-icons/apps/scalable/brave-browser.svg"
  - "/opt/flatpak-icons/apps/scalable/obsidian-icon.svg"
  - "/opt/flatpak-icons/apps/scalable/burp.svg"
  - "/opt/flatpak-icons/apps/scalable/caido.png"
  - "/opt/flatpak-icons/apps/scalable/flameshot.png"

parrot_apps:
  - name: "sublime-text"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/sublime-text.desktop"
    id: 261
  - name: "vscode"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/vscode.desktop"
    id: 271
  - name: "firefox"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/firefox.desktop"
    id: 281
  - name: "brave-browser"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/brave-browser.desktop"
    id: 291
  - name: "obsidian"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/obsidian.desktop"
    id: 301
  - name: "burp-suite"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/burp-suite.desktop"
    id: 311
  - name: "caido"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/caido.desktop"
    id: 321
  - name: "flameshot"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/flameshot.desktop"
    id: 331


ubuntu_apps:
  - name: "sublime-text"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/sublime-text.desktop"
    id: 89
  - name: "vscode"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/vscode.desktop"
    id: 99
  - name: "firefox"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/firefox.desktop"
    id: 109
  - name: "brave-browser"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/brave-browser.desktop"
    id: 119
  - name: "obsidian"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/obsidian.desktop"
    id: 129
  - name: "burp-suite"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/burp-suite.desktop"
    id: 139
  - name: "caido"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/caido.desktop"
    id: 149
  - name: "flameshot"
    desktop: "{{ ansible_facts['env']['HOME'] }}/.config/mate/panel2.d/default/launchers/flameshot.desktop"
    id: 159


shortcut_name: "flameshot"
shortcut_command: "flameshot gui"
shortcut_binding: "<Alt>a"
new_slot: "custom6"
new_path: "/org/mate/desktop/keybindings/{{ new_slot }}/"
