---
- name: "Building Parrot"
  hosts: localhost
  connection: local
 
  vars_files:
    - "{{ ansible_env.HOME }}/.ansible/secrets.yml"
 
  pre_tasks:
    - name: Verify GitHub Authentication
      uri:
        url: "https://api.github.com/rate_limit"
        method: GET
        headers:
          Authorization: "token {{ github_api_key }}"
      register: auth_check
      failed_when: auth_check.json.rate.limit != 5000

    - name: Show Current Rate Limit
      debug:
        msg: "Authentication Successful! Remaining requests: {{ auth_check.json.rate.remaining }} / {{ auth_check.json.rate.limit }}"
 
  roles:
    - role: "roles/tmux-config"
    - role: "roles/terminal-config"
    - role: "roles/tools-installation"
    - role: "roles/vscode-installation"
    - role: "roles/browser-customization"
    - role: "roles/logging-config"
    - role: "roles/system-config"
    - role: "roles/obsidian-git"
    - role: "roles/docker-bloodhound"
    - role: "roles/desktop-customization"
