---
- name: "Building Parrot"
  hosts: localhost
  connection: local
  tasks:
    - name: "Write File"
      debug:
        msg: "Parrot is being built..." 
  roles:
    - role: "roles/tmux-config"
    - role: "roles/terminal-config"
    - role: "roles/tools-installation"
    - role: "roles/vscode-installation"
    - role: "roles/browser-customization"
    - role: "roles/logging-config"