---
- name: "Building Parrot"
  hosts: localhost
  connection: local
  tasks:
  vars_files:
    - "{{ ansible_env.HOME }}/.ansible/secrets.yml"
  roles:
    - role: "roles/tmux-config"
    - role: "roles/terminal-config"
    - role: "roles/tools-installation"
    - role: "roles/vscode-installation"
    - role: "roles/browser-customization"
    - role: "roles/logging-config"
    - role: "roles/system-config"
    - role: "roles/obsidian-git"
    - role: "roles/docker-bloodhound"
    - role: "roles/desktop-customization"
