---
- name: "Check the existence of caido-latest.json file in /tmp"
  stat: 
    path: /tmp/caido-latest.json
  register: latest_caido_json_file
  changed_when: false

- name: "Downloading Latest Version of Caido"
  uri:
    url: "https://api.github.com/repos/caido/caido/releases/latest"
    method: GET    
    headers:
      Authorization: "token {{ github_api_key }}"
    dest: /tmp/caido-latest.json
    mode: '0640'
  when: latest_caido_json_file.stat.exists == false

- name: "Check the presence of /tmp/downloadcaido.sh"
  stat:
    path: /tmp/downloadcaido.sh
  register: caido_download_file
  changed_when: false

- name: "Copy downloadcaido.sh to /tmp/downloadcaido.sh"
  copy:
    src: downloadcaido.sh
    dest: /tmp/downloadcaido.sh
    mode: 0760
  when: caido_download_file.stat.exists == false

- name: "Extracting Caido URL from JSON"
  shell: /tmp/downloadcaido.sh
  register: caido_url
  changed_when: false

- name: "Check the existence of /usr/local/bin/caido"
  stat:
    path: /usr/local/bin/caido
  register: caido_binary_bash
  changed_when: false

- name: "Check the existence of /opt/caido"
  stat:
    path: /opt/caido
  register: caido_binary
  changed_when: false

- name: "Downloading Caido"
  get_url:
    url: "{{ caido_url.stdout }}"
    dest: /opt/caido
    mode: '0755'
  become: true
  become_method: sudo
  when: caido_binary.stat.exists == false and ansible_distribution == "Ubuntu"

- name: "Making Caido executable"
  shell: |
    bash -c "echo -e '#!/bin/bash\n/opt/caido --no-sandbox' > /usr/local/bin/caido" 
    chmod +x /usr/local/bin/caido
  args:
    executable: /bin/bash
  become: true
  become_method: sudo
  when: caido_binary_bash.stat.exists == false and ansible_distribution == "Ubuntu"
