---
- name: "Copying obsidian-download.sh to /tmp"
  copy:
    src: "obsidian-download.sh"
    dest: "/tmp/obsidian-download.sh"
    mode: 0755
  
- name: "Check If Obsidian Exists"
  stat:
    path: "/opt/obsidian"
  register: obsidian_exists
  changed_when: false

- name: "Check the existence of /tmp/obsidian-release-metadata.json"
  stat:
    path: "/tmp/obsidian-release-metadata.json"
  register: obsidian_release_metadata
  changed_when: false

- name: "Download latest Obsidian release metadata"
  get_url:
    url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
    dest: /tmp/obsidian-release-metadata.json
    mode: "0644"
  when: not obsidian_release_metadata.stat.exists
  
- name: "jq latest obsidian version from obsidian-release-metadata.json"
  set_fact:
    obsidian_latest_version: "{{ (lookup('file', '/tmp/obsidian-release-metadata.json') | from_json).tag_name }}"

- name: "Check the existence of /opt/current_versions directory"
  stat:
    path: "/opt/current_versions"
  register: current_versions
  changed_when: false

- name: "Creating /opt/current_versions directory"
  file:
    path: "/opt/current_versions"
    state: directory
    mode: 0755
  become: true
  become_method: sudo
  when: not current_versions.stat.exists

- name: "Check the presence of /opt/current_versions/obsidian_current_version.txt"
  stat:
    path: "/opt/current_versions/obsidian_current_version.txt"
  register: obsidian_version_file
  changed_when: false

- name: "Writing Current Version of Obsidian to file /opt/current_versions/obsidian_current_version.txt"
  copy:
    dest: "/opt/current_versions/obsidian_current_version.txt"
    content: "{{ obsidian_latest_version }}"
    mode: "0644"
  become: true
  become_method: sudo
  when: not obsidian_version_file.stat.exists

- name: "Read Current Version of Obsidian from file /opt/current_versions/obsidian_current_version.txt"
  set_fact:
    obsidian_current_version: "{{ lookup('file', '/opt/current_versions/obsidian_current_version.txt') }}"
  when: obsidian_version_file.stat.exists

- name: "Compare obsidian_current_version with obsidian_latest_version"
  set_fact:
    obsidian_update_required: "{{ obsidian_current_version != obsidian_latest_version }}"
  when: obsidian_version_file.stat.exists

- name: "Executing Bash Script to Install Obsidian"
  shell: "/tmp/obsidian-download.sh"
  when: obsidian_update_required
  ignore_errors: true

- name: "Store the latest version in the Current Version File"
  copy:
    dest: "/opt/current_versions/obsidian_current_version.txt"
    content: "{{ obsidian_latest_version }}"
    mode: "0644"
  become: true
  become_method: sudo
  when: obsidian_update_required

- name: "Check if Tech-Notes Exists"
  stat:
    path: "{{ ansible_facts['env']['HOME'] }}/Notes/Tech-Notes/.git"
  register: tech_notes
  changed_when: false

- name: "Check if Old-Notes Exists"
  stat:
    path: "{{ ansible_facts['env']['HOME'] }}/Notes/Old-Notes/.git"
  register: old_notes
  changed_when: false

- name: "Check if Notes Exists"
  stat:
    path: "{{ ansible_facts['env']['HOME'] }}/Notes"
  register: notes
  changed_when: false

- name: "Create Directory ~/Notes"
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/Notes"
    state: directory
    mode: 0755
  when: not notes.stat.exists

- name: "Clone Tech-Notes via Git"
  git:
    repo: "git@github.com:perumal-j/Tech-Notes.git"
    dest: "{{ ansible_facts['env']['HOME'] }}/Notes/Tech-Notes"
    accept_hostkey: yes
  when: not tech_notes.stat.exists

- name: "Clone Old-Notes via Git"
  git:
    repo: "git@github.com:perumal-j/Old-Notes.git"
    dest: "{{ ansible_facts['env']['HOME'] }}/Notes/Old-Notes"
    accept_hostkey: yes
  when: not old_notes.stat.exists