#SPDX-License-Identifier: MIT-0
---
UVtools:
  - impacket
  - sshuttle

GithubRepositories:
  - url: "https://github.com/ShutdownRepo/pywhisker"
    destination: "tmp/pywhisker"

repositories: 

  - name: bloodyAD
    url: "https://github.com/CravateRouge/bloodyAD"
    destination: "{{ ansible_env.HOME }}/bloodyAD"

  - name: targetedKerberoast
    url: "https://github.com/ShutdownRepo/targetedKerberoast"
    destination: "/tmp/targetedKerberoast"

  # - name: pywhisker
  #   url: "https://github.com/ShutdownRepo/pywhisker"
  #   destination: "/tmp/pywhisker"