---
- name: "Building Obsidian Git"
  hosts: localhost
  connection: local
  tasks:
    - name: "Writing File"
      debug:
        msg: "Obsidian Git is being built..." 
  roles:
    - role: "roles/obsidian-git"
  