---
- name: "Building Parrot"
  hosts: localhost
  connection: local
  tasks:
    - name: "Write File"
      debug:
        msg: "Parrot is being built..." 
  roles:
    - role: "roles/python-installation"
  