---
- name: "Install and configure AuditD"
  hosts: localhost
  connection: local
  tasks: 
    - name: "Installing RubyGems"
      apt:
        name: ruby-full
        state: present
      become: true
      become_method: sudo


    - name: "Installing tools from Gems"
      gem:
        name: "{{ item }}"
        state: present
        user_install  : false
        install_dir: "/home/perumalj/.local/gems"
      loop:
        - logger
        - stringio
        - winrm
        - builder
        - erubi
        - gssapi
        - gyoku
        - httpclient
        - logging
        - little-plugger
        - nori
        - rubyntlm
        - winrm-fs
        - evil-winrm
