#SPDX-License-Identifier: MIT-0
---
- name: "Downloading repositories from GitHub"
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.destination }}"
  loop: "{{ GithubRepositories }}"
  register: downloaded_repos

- name: "Debug pywhisker_files"
  debug:
    msg: "{{ downloaded_repos.results }}"

- name: "Search for pywhisker.py in downloaded repositories"
  find:
    path: "{{ item.item.destination }}"
    patterns: "pywhisker.py"
    recurse: true
  loop: "{{ downloaded_repos.results }}"
  register: pywhisker_files
